### ISSUE TITLE
RFE: Syntax highlighting in JSON view

### ISSUE THREAD

**Issue by gitblit** [redis/RedisDesktopManager#1629]
Would it be possible to integrate Pygments or something similar to offer syntax highlighting for the JSON view?
##

**Comment by uglide** [comment]
Sorry for late reply. Yes, it's possible. I will implement this feature in 0.7.8 release

**Comment by gitblit** [comment]
Nice! :+1:

**Comment by iworker** [comment]
It could be a very nice feature. @uglide Maybe you have a plan how to implement it? :)

**Comment by uglide** [comment]
@iworker 
There are 2 (both hard:)) ways to implement it
1st - QSyntaxHighlighter https://stackoverflow.com/questions/14791360/qt5-syntax-highlighting-in-qml
2nd - forking one of JS highlighting libraries like https://prismjs.com/ and modifying it to support inline css styling instead of classes - it's required for correct rendering in QML TextArea with limited HTML rendering capabilities

**Comment by iworker** [comment]
@uglide probably, it'd be better to split this feature into 2 parts:
1. Simple JSON formatting (just using something like <pre> tags and some simple pretty print of json + some validator to identify that value is in json format);
2. Syntax highlighting;
I think 1st is much easier than 2nd and could be implemented without any 3rd parties solutions but it'll give almost the same value.

**Comment by uglide** [comment]
@iworker JSON formatter is already implemented :) and you have already know it since you removed your comment

**Comment by iworker** [comment]
@uglide Yes it's the reason why I removed that comment. I opened RDM and discovered that formatter is already implemented :)
btw I think the 2nd way of highlighter implementation is easier and better.

**Comment by uglide** [comment]
Added in 2019.0 (thanks to @borislobanov92)
