### ISSUE TITLE
Support for unix sockets?

### ISSUE THREAD

**Issue by rayshan** [redis/RedisDesktopManager#1751]
Hello, thanks for all the hard work on this. Is there a way to connect to unix sockets? E.g. `/tmp/redis-app.sock`. I can only seem to be able to enter `host`:`port` in the Add New Connection dialog. Thanks.
##

**Comment by uglide** [comment]
Hello @rayshan 
This feature not implemented yet. Your suggestion is very useful and I will add this feature in backlog

**Comment by nq-ebaratte** [comment]
I was confronted with the same problem; a temporary workaround consists in redirecting a local socket to the unix domain socket, for instance with [socat](http://sourceforge.net/projects/socat)

```
 socat -v tcp-l:6379,reuseaddr,fork unix:/tmp/redis.sock
```

**Comment by simonwiles** [comment]
thank you @nq-ebaratte!

**Comment by kanevbg** [comment]
+1

**Comment by slavaGanzin** [comment]
Why the hell "wontfix"? It's basic and easy feature.

**Comment by uglide** [comment]
@slavaGanzin Yes, it's easy to add local unix socket connection and *No, it's quite hard to support it in common case*. Unix socket is used on production environment and RDM needs to support unix sockets over SSH tunnel which is not that easy (underlying libssh2 library does not support forwarding for unix sockets).

**Comment by slavaGanzin** [comment]
@uglide I'm talking about plain "same host" unix socket. So you can choose to use TCP stack (e.g. host:port) or unix socket file (/tmp/redis.sock). Without fancy tunneling, which I think is a user responsibility and trouble.

Most users don't bother, because they have open `localhost:6379`, but as you may know tcp is relatively (up to 33%) slower than unix socket: http://momjian.us/main/blogs/pgblog/2012.html#June_6_2012
