### ISSUE TITLE
Quotation marks.

### ISSUE THREAD

**Issue by nickbrandwood** [redis/RedisDesktopManager#1860]
I'm running the RedisDesktopManager on Windows x64.

When I put a command with quotes like 
SET Var1 "hello world" 
I get a syntax error. 
There seems to be an issue with the quotes.

![image](https://cloud.githubusercontent.com/assets/7839840/3218639/edc65cf0-efec-11e3-83c3-a4d62ac74ddc.png)

I've tried using double quotes...
![image](https://cloud.githubusercontent.com/assets/7839840/3218634/dcf8cdea-efec-11e3-9a1b-b01d2e2b493f.png)

What am I doing wrong?

**Comment by uglide** [comment]
Hello, this bug fixed in 0.7.7. Unfortunately this version is not released yet, but you can use latest windows night build http://redisdesktop.com/builds/redis-desktop-manager-0.7.7.35.exe

![6-9-2014 8-16-27 pm](https://cloud.githubusercontent.com/assets/1655867/3219833/d631277a-eff9-11e3-9c09-e4ceb2c0638f.jpg)

If you have any suggestions, please leave your feedback in this ticket https://github.com/uglide/RedisDesktopManager/issues/1738

**Comment by nickbrandwood** [comment]
Thanks, I thought I was finding it harder than it should have been!!
