### ISSUE TITLE
Implement lazy-loading in connections tree

### ISSUE THREAD

**Issue by ovanes** [redis/RedisDesktopManager#1875]
As I can conclude from the behaviour right now, all the keys are rendered at once. One of my DBs has 4.7 million keys... After an hour of downloading and rendering the keys RDM is still not ready, uses 200% CPU on Mac Book Pro Retina with 16 GB RAM and 8 cores. Within this hour my battery went from 100% to 28% :(

**Comment by digipigeon** [comment]
+1 - I don't know why the website says: "Works with BIG databases, Do you have over 1 Million keys in redis? It's not a problem." I am dealing with 10m keys (which in the grand scheme of things is not big), when I had 1m it took about 3 minutes to load, now its completely unusable on that database.

**Comment by uglide** [comment]
@digipigeon in most cases if you load all keys - you are doing something wrong.
To reduce key space you should use filter in connection settings.

Also if you need this improvement - you should [donate](https://www.bountysource.com/issues/2671495-render-keys-in-chunks) or create pull request (at least with design proposal) otherwise it will be in backlog for a long time

**Comment by digipigeon** [comment]
@uglide The application does not inform me that I am doing anything wrong, nor does it advise me that a filter would be useful or by default present me with a filter to enter when I open the tree item. I am just clicking on tree items in a way which logically makes sense for a novice at using this application.

I will consider using a filter in the future and should I be able to wrangle this application to work for me I will donate. Thank you.

**Comment by uglide** [comment]
Implemented in 0.8.8
