### ISSUE TITLE
Recursive parsing of MultiBulk replies not supported

### ISSUE THREAD

**Issue by KevinBurton** [redis/RedisDesktopManager#3318]
If rdm is connected to a sentinel the command (from a console) 'SENTINEL masters' hangs and after about 2 minutes I get the message
Recursive parsing of MultiBulk replies not supported
The same thing occurs when I  issue the command 'SUBSCRIBE +odown +failover-master +switch-master'
I also get the same "hanging" behavior when I issue 'exit'

**Comment by uglide** [comment]
I already have done some improvements in 0.8.0 branch:

![screenshot from 2015-02-13 19 47 17](https://cloud.githubusercontent.com/assets/1655867/6192292/24e5bdc6-b3b9-11e4-88cd-78a40804802b.png)
Currently, it looks really ugly, but it works :)

I will implement pretty printing in 0.8.0 - #3319

**Comment by KevinBurton** [comment]
Is there a binary Windows version available?

**Comment by uglide** [comment]
Currently - no, but you have several options here:
1. [Build RDM by yourself.](https://github.com/uglide/RedisDesktopManager/wiki/Development-Guide) On Windows it's easy, because all deps already have built. But of course this option will take some time.
2. [Sign up for beta testing](https://docs.google.com/forms/d/1wJSvJfGsv2NhCG9Eoxayad28XV1EtaLk-C0Zjpa2B9k/viewform). First beta build of 0.8.0 will be released on the next week. 

If you have any questions, please feel free to join RDM chat : https://gitter.im/uglide/RedisDesktopManager?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by KevinBurton** [comment]
I followed all of the steps (I have VS 2013 so I am assuming the a "recent" version of VS is OK) but I get the attached output. A number of warnings and errors.
![image](https://cloud.githubusercontent.com/assets/2643566/6193747/f25a7c50-b383-11e4-985c-dab0a12620b1.png)

**Comment by uglide** [comment]
`I have VS 2013 so I am assuming the a "recent" version of VS is OK`
Version of msvc meters, because RDM has pre-builded libs only for msvc2012.

`I get the attached output.`
I have fixed this incompatibilities in latest commits. Make `git pull` and rebuild with vs 2012. Or try this installer: http://redisdesktop.com/builds/redis-desktop-manager-0.7.9.36.exe

**Comment by KevinBurton** [comment]
I tried the latest from GitHub but there seems to be a missing file:
