### ISSUE TITLE
Did not start at Xubuntu 14.04.2

### ISSUE THREAD

**Issue by dcromster** [redis/RedisDesktopManager#3391]
This application failed to start because it could not find or load the Qt platform plugin "xcb".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
/usr/bin/redis-desktop-manager: line 4: 22825 Aborted                 (core dumped) $DIR/rdm

**Comment by dcromster** [comment]
How to fix it: Make symlink from /usr/share/redis-desktop-manager/lib/plugins/ to  /usr/share/redis-desktop-manager/bin/

**Comment by dcromster** [comment]
Also RDM needs libqt5quick5 library.

**Comment by gshmu** [comment]
:+1:

**Comment by uglide** [comment]
I found issue with Ubuntu deb package recently which probably will fix this one too.
I will close this issue, because XUbuntu is not offically supported by RDM. But if you need it, you can easily build it from source, [it's easy](https://github.com/uglide/RedisDesktopManager/wiki/Build-from-source#ubuntu)!

**Comment by gshmu** [comment]
@uglide I think this issue should close after ubuntu fixed it.
