### ISSUE TITLE
8RC4: Crash after a while it is running

### ISSUE THREAD

**Issue by aferrandi** [redis/RedisDesktopManager#3463]
I just open it, connect to a redis cache,do something else and when I come back to it it has crashed.

![image](https://cloud.githubusercontent.com/assets/1436546/9731380/e392fda0-561c-11e5-9bb6-71836053f190.png)

It runs on a VM i Azure.
It uses stunnel to connect to the redis cache 
The cache can contain around 100-200 keys with a many MBytes of data,.

I am not able to open issue 63, as described in the message box.

**Comment by roynasser** [comment]
I'm getting tons of these errors constantly...  Also getting keys showing as "Failed" instead of a keyname...

RDM is unusable at this point...  I dont know why I upgraded, but probably non-stable versions should have a better warning... I'm going to try to downgrade

**Comment by uglide** [comment]
@RVN-BR Please provide some useful information (like steps to reproduce) if you really want to help.

**Comment by roynasser** [comment]
Thats the problem... just leacving it loaded causes it... I always submit the reports is there any info I can provide for you to look up these reports?
- It crashes intermittently just leaving the app open
- it crashes when connecting
- crashes when double clicking a DB
- its extremely sporadic... I havent had any similar issues since v 0.6 or 0.5 which I had started using...

**Comment by ronnyek** [comment]
I've seen this happen too... just letting it sit there, sometimes crashing as many as 5 times in an hour.. .almost seems related more to time its running than what you are doign or what you have done.

Id also expect the crash reports to be sent to someone who might be able to decipher and fix (which is good because I'm given no additional information once it crashes) many keys, but I'll browse to a key, get a value... start using another program... what seems to be a completely random interval... bam.. .crash

**Comment by uglide** [comment]
No feedback was provided since 0.8.0 release so I assume that problem was fixed.
