### ISSUE TITLE
Screen flash/blank rapidly while app starts

### ISSUE THREAD

**Issue by smiket** [redis/RedisDesktopManager#3584]
I have a multiple monitor setup (laptop, and 2 large screens.  When I start the app, all screens flash / go to black etc rapidly, and everything finally goes back to normal.

Thanks for such a nice product - hope this helps.
Steve
##

**Comment by uglide** [comment]
Hello @smiket 
Thanks for the feedback. Which OS & version do you use?

**Comment by smiket** [comment]
I am running Windows 7 (x64).

**Comment by 12343954** [comment]
same problem, on Windows Server 2008 r2, redis-3.2.1, RDM-0.8.8

but i found this on official website
http://docs.redisdesktop.com/en/latest/known-issues/

Black screen instead of Welcome tab on Windows under VirtualBox
Remove opengl32sw.dll and Copy this [dll](https://raw.githubusercontent.com/uglide/RedisDesktopManager/5f99aa22aa84dc55b5c9858de28d68facd1c58b7/build/windows/installer/resources/rdp_fix/opengl32.dll) to RDM installation folder

NOT solved
