### ISSUE TITLE
no rdm.app for MacOS build

### ISSUE THREAD

**Issue by isadon** [redis/RedisDesktopManager#3659]
RDM Version:0.87
Environment (OS name and version): MacOS 10.11.6
Redis Server Version: 3.2.1

Steps to reproduce:

Follow instructions on how to build rdm for mac using QT Creator. After build completes notice only a binary is built.

Expected result: 

A rdm.app is built or instructions for how to create the rdm.app from rdm binary are posted.

Actual Result: 
After build completes notice only a binary is built.

**Comment by uglide** [comment]
I do not provide any help with building RDM from source anymore. You can download ready-to-use rdm.dmg with paid subscription from redisdesktop.com. It's only $1.99
More info here https://redisdesktop.com/subscribe

**Comment by krazyjakee** [comment]
Your documentation isn't accurate. There are deliberately missed steps. This is well documented in these issues.

People would gladly donate or pay for premium support contracts, automatic updates and premium features. Blackboxing the compilation and then charging for binaries makes you an asshole.

**Comment by uglide** [comment]
@krazyjakee Unfortunately only a few people donated to RDM and nobody contacted me for "premium support contracts". Documentation is open and everybody can update it and receive free contributor subscription. So I'm not blackboxing anything and if my intention to develop open-source GUI for redis is assholing -  call me so.

**Comment by krazyjakee** [comment]
> only a few people donated to RDM

because people believe they can compile the source, then find they can't because the documentation is wrong and then there is no chance they are going to pay you.

> nobody contacted me for "premium support contracts"

because you don't advertise them.

> Documentation is open and everybody can update it

These kinds of contributions are rare, even in large scale open source projects. The core team should at least attempt to keep them up to date. This is not an excuse for bad documentation, especially when the final product is behind a paywall. Doesn't matter who is responsible for updating documentation as long as you're accepting payment, you're an asshole.

**Comment by uglide** [comment]
> because people believe they can compile the source

hah, I'm talking about times when RDM binaries were freely available for all platforms (Windows, OS X and Ubuntu)

> Doesn't matter who is responsible for updating documentation as long as you're accepting payment, you're an asshole.

Could you fix some issues and add new features in this project for free?
