### ISSUE TITLE
Does not work with the latest Redis 3.2.100 with Protected Mode

### ISSUE THREAD

**Issue by win32nipuh** [redis/RedisDesktopManager#3780]
RDM Version: latest
Environment (OS name and version): Windows 10, Windows Server 2012

Redis Server Version: <br>
3.2.100
https://github.com/MSOpenTech/redis/releases

Steps to reproduce:

1. run RDM

2. try to connect to Redis

3. 

Expected result: 

Actual Result: Error

**Comment by uglide** [comment]
I tested both 0.8.8 and 0.9.0-alpha3 on Windows 10 +  Redis Server v3.2.100 and it works:

RedisDesktopManager v0.8.8 on Windows 10 + Redis Server v3.2.100:
![image](https://cloud.githubusercontent.com/assets/1655867/21046081/9447746c-be0b-11e6-8427-486cdb8b0d3f.png)

RedisDesktopManager v0.9.0-alpha3 on Windows 10 + Redis Server v3.2.100:
![image](https://cloud.githubusercontent.com/assets/1655867/21046121/c8e119d0-be0b-11e6-9923-96b4465ca9a4.png)

Which kind of error do you have?

**Comment by cajnoj** [comment]
Just had a similar problem of RDM crashing when connecting to a server with protected mode on. Instead of showing a verbose error message, the client just says that it cannot connect when pressing "test connection" in the connection configuration dialog, and crashes after a short while, when double-clicking on a configured connection.
Workaround: Turn protected mode off or set authentication for connection

What I'd like to see is a more verbose response from the client. It was really hard to find the problem.

**Comment by uglide** [comment]
@cajnoj Thanks for the detailed feedback.
