### ISSUE TITLE
Package not signed.

### ISSUE THREAD

**Issue by afink-amd** [redis/RedisDesktopManager#3849]
RDM Version: 0.8.8.32
Environment MacOS 10.12 
Redis Server Version: n/a

Steps to reproduce:

1. Doubleclick RDM

You get a dialog saying it can not be opened because its from a unknown developer.
Simply, you didnt add a code signature which makes RDM a ideal candiate as a troyan transporter...

**Comment by uglide** [comment]
Duplicate #3655

**Comment by andreasfink** [comment]
This is not a duplicate of 3655 as 3655 talks about Windows. This is about the normal code signing of MacOS X which every osx binary has by default if properly compiled. Its like adding one line to the Makefile or compiling with Xcode and its done. Its important because people are not be able to run it under MacOS X in the default security settings. You can only run it by right clicking and opening and then accepting the security dialog which most normal users dont know.

**Comment by uglide** [comment]
Unfortunetly I don't have membership in Apple Developer Program. That's  why I cannot sign binaries on OSX with `codesign`. If you can/want you may donate $99 via Bountysource and I will sign OSX binaries for next year.

**Comment by afink-amd** [comment]
you dont need membership for that.
you only need a developer ID

But I'm happily to donate you the 99 for the good work..

**Comment by uglide** [comment]
Maybe I missing something, but from my understanding developer ID = membership in Apple developer program.
