### ISSUE TITLE
the release 0.9.1 cannot filter by "*key*"

### ISSUE THREAD

**Issue by chenfei2341** [redis/RedisDesktopManager#4060]
RDM Version: 0.9.1.771 <br>
Environment (OS name and version): win7 64 sp1<br>
Redis Server Version: 3.0.504 for windows <br>

Steps to reproduce:

1.  connect redis OK. <br>

2. choose open keys filter, input "11*", i can find the right results. 

3. but when input "*11*", I can't find any key

Expected result: the right results

Actual Result: empty

**Comment by BHare1985** [comment]
I also have experienced this issue

**Comment by iworker** [comment]
@chenfei2341 @BHare1985 the problem is that there is regexp filtering on client side and server filtering in server side. When you're using `*key*`, redis understand what is it and correctly filtering. But when then regexp tries to apply this to keys found by redis, these keys got lost.
I've tried to fix this (changed sending template to redis to sending just "*" and filtering on client side). Don't know if it good solution. We'll see.
If it'll be applied then you'll be able to search any keys by any valid regexp.
