### ISSUE TITLE
Distribute RDM with flatpak

### ISSUE THREAD

**Issue by jay763190097** [redis/RedisDesktopManager#4178]

**Comment by uglide** [comment]
Because snapcraft provides automatic builds from github with autoupdates and available out of the box on the most popular  Linux distribution

**Comment by claudioap** [comment]
Sorry for digging an old issue but I don't find my comment a worthy reason to open yet another bug.

While Ubuntu runs Flatpak just fine with it being developed as a distro-agnostic solution, Snap has undesirable quirks, specially in every distro that is not Ubuntu. And the fact that it is centralized on a single hardcoded repository controlled by a private party that has an habit of killing products and services; or that the daemon "needs" to pollute home folder instead of following the XDG standards, are kind of red flags for some people.

I'm not stating that your decision of picking snap is bad, it simply happens that flatpak is IMO a better solution when considering the fact that there are more distros. You might not have automatic builds, but even semiannual updates could be awesome. Also, Ubuntu has more users but a substantially lower ratio of developers per capita than distros such as Debian, Fedora, Arch and Gentoo; and RDM is not exactly a software that is used by the typical average user.

If it matters, the context that led me to "complain" was an Arch update that broke RDM (python 3.8 -> 3.9). I'm going to workaround it with an Appimage since I find it preferable over snaps.

**Comment by uglide** [comment]
Hello @claudioap 
Thanks for the feedback,

Could you clarify are you voting for Flatpak or AppImage?

**Comment by claudioap** [comment]
I'm voting for Flatpak. Both are fine distro-neutral solutions, but Flatpak integrates with the environment and shares runtimes just like Snap (but without proprietarisms, favouritisms and some odd quirks). 

What I tried to say is that for the time being I'm using an AppImage (which I downloaded from [here](https://github.com/pidario/rdm-build/releases/)).

**Comment by ariasmn** [comment]
Hi!

[Here ](https://github.com/ariasmn/rdm-flatpak)I link you my repository with the needed files for the Flatpak packaging. You need to follow the tutorial I linked to publish the app on Flathub.

Also, I haven't fully tested the app, but it seems like it is working properly, except for the visual bug that I mention on my repository.

I don't want to be the one to upload the app to Flathub since I think that the main developer should be the one to do so. If I can do anything more to make the process easier, please let me know.

Thanks!

**Comment by uglide** [comment]
@ariasmn Thanks a lot for sharing your flatpak packaging.
I've added small improvements to it in my fork and submitted it to Flathub https://github.com/flathub/flathub/pull/2437

**Comment by ariasmn** [comment]
@uglide Super glad that I could help!

I see that the build is failing in Flathub (even though locally the build finish without errors). I will keep an eye on the Flathub PR to see if I can help.
Also, I will let you know once the maintainers of the KDE QT runtime answer about the weird styling bug.

Thank you so much!

**Comment by uglide** [comment]
RDM was added to Flathub. Currently without SSH tunnel support and Numpy/Pandas pretty formatting. All issues please report here https://github.com/flathub/dev.rdm.RDM

@ariasmn thanks for all your efforts to make it happen!
