### ISSUE TITLE
Sometimes the GUI stuck

### ISSUE THREAD

**Issue by AlexMasonQi** [redis/RedisDesktopManager#4182]
RDM Version: 0.9.3.817<br>
Environment (OS name and version): Windows 10 Pro x64<br>
Redis Server Version: 4.0.11<br>

Issue:<br> Sometimes the software can stuck and flashback
Request: <br>When I refresh a database in my redis server

**Comment by mvanderlee** [comment]
Sometimes? All the ~~fucking~~ time. 
When I click on a server to edit the settings, it blocks because it blocks on network calls. 
I know it's not going to work, because I need to update the IP. Don't make me wait for the connection to timeout. 

1) Don't make network calls blocking, please look into adding async behaviour. ~add some damn async behaviour~
2) Don't try to connect on single click, only double click. 

~~Especially now that you're charging money.. fix your shit.~~

Edit: Was particularly frustrated with things not working that day, RDM issues was where I  lost it and took my anger out on. My apologies.

**Comment by uglide** [comment]
@MichielVanderlee you can use the right mouse button to select connection without trying to connect

**Comment by uglide** [comment]
@MichielVanderlee 
![image](https://user-images.githubusercontent.com/1655867/46069657-a7365600-c184-11e8-89e6-b199195f83c6.png)
Will be released shortly as part of 0.9.8 release :)

**Comment by mvanderlee** [comment]
Great, thanks @uglide
