### ISSUE TITLE
[UI display defect]win10 1080P DPI 150% UI issue

### ISSUE THREAD

**Issue by shryan-bin** [redis/RedisDesktopManager#4272]
RDM Version: 0.9.8<br>
Environment (OS name and version): <br> win10 1067
Redis Server Version: <br>

Steps to reproduce:

1. Doule click redis desk top management
2. Click setting

Expected result:  all setting items can be displayed 

Actual Result:  All items can not be displayed after "Custom value View Formatters" in 1080P with 150% DPI

**Comment by uglide** [comment]
@shryan-bin please provide screenshots. Also you have specified wrong version of windows 10, Are you on Windows 10 1607?

**Comment by shryan-bin** [comment]
Yes, I am on win10 1067. I am not sure this is related with win version. I attached the screenshot. Please check.
<img width="958" alt="2018-10-29 10_46_35-setting" src="https://user-images.githubusercontent.com/12909476/47626852-2cd46980-db68-11e8-9b61-52903ae27685.png">

There should be a scroolbar on the right side. In Mac OS, it is ok.

**Comment by crowlex** [comment]
Hello I have the same problem on my laptop. I have Ubuntu 18.04  and have same Ubuntu on another PC where RDM works as well. Btw it happens when I install RDM from snap. If I build it from source RDM works perfect!!!

![screenshot from 2018-10-31 21-34-30](https://user-images.githubusercontent.com/5450006/47814034-569eb380-dd55-11e8-889e-5384f334f75c.png)
![screenshot from 2018-10-31 21-36-05](https://user-images.githubusercontent.com/5450006/47814093-78983600-dd55-11e8-94ec-b6b0264fde39.png)

**Comment by phillijw** [comment]
There are a lot of DPI issues. The app looks really ugly on my computer that has a 4k screen with two 1080p monitors connected. The DPI is just a bit screwy.

**Comment by uglide** [comment]
@phillijw OS? screenshots?

**Comment by phillijw** [comment]
win10

I think the text is larger than it should be and maybe some buttons/icons seem large. I've used the app on just 1080p screens and it looked a lot better in those cases.

![image](https://user-images.githubusercontent.com/467889/48012911-b9db6d80-e0e8-11e8-8b20-b550ef3525c1.png)

**Comment by uglide** [comment]
@phillijw It doesnt look like "really ugly" :) You can change font size to smaller in Settings

**Comment by phillijw** [comment]
@uglide "Ugly" may have been the wrong word. I've used the app previously and it was very nice. Something with the DPI makes it behave and look strangely to me on this PC. Changing the font size helps a bit but the icons are still oversized. Some stuff just seems to have a DPI issue for some reason. Some screens I can't make smaller even though they're way too big.

Here's another example:
![image](https://user-images.githubusercontent.com/467889/48014019-5a329180-e0eb-11e8-9e39-f75c08e4e801.png)

**Comment by uglide** [comment]
@phillijw thanks for the detailed feedback. Could you please specify physical size of your 4k screen (22"/24" etc)
It's quite hard to adjust the scaling of app for all because I've received a lot of opposite feedback from users with tiny 4k laptops. But probably adding some setting in RDM itself for upscale/downscale icons can help for both cases (upscaling on tiny 4k screens and downscale on large 4k screens)

**Comment by phillijw** [comment]
@uglide The 4k screen is ~15" laptop screen with 175% scaling and the 1080p screens are 24" with 100% scaling.
