### ISSUE TITLE
App Crashes When Expanding Nested Keys

### ISSUE THREAD

**Issue by lots0logs** [redis/RedisDesktopManager#4564]
**Describe the bug**
When I try to expand a group of nested keys that have a large number of keys the app crashes. It was working fine in previous version.

**To Reproduce**
1. Select your database
2. Try to expand a large group of keys.
4. App crashes

**Expected behavior**
App not to crash

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Arch Linux
 - Redis-Server 4.0.9

**Comment by uglide** [comment]
Please specify RDM build version or commit of source tree if it was built from source

**Comment by uglide** [comment]
@lots0logs please provide more details :arrow_double_up:

**Comment by lots0logs** [comment]
@uglide Here is the [PKGBUILD](https://github.com/Antergos/antergos-packages/blob/master/antergos/redis-desktop-manager/PKGBUILD) file and the [build log](https://build.antergos.com/build/9197). Let me know if there's any other information I can provide. Cheers!

**Comment by uglide** [comment]
@lots0logs thanks. Please also specify how large your "a large group of keys." is, is it plain keys or namespaced, etc. It will help me to reproduce the issue.

**Comment by lots0logs** [comment]
@uglide Sorry for the delay. The group has ~15,600 keys. They are all in the format `cnchi14:install:12345`

**Comment by modiho** [comment]
I'm running into the same problem. When trying to expand into a list with ~261 keys, rdm crashes with a Segmentation Fault. I'm running redis v2.8.23 on Debian Jessie, and my host OS is Arch Linux as well, running rdm v2019.0. It was working fine in v0.9.9.

A crash also happens when I open a connection, select a DB, and then click on "Edit Connection". Last log entry before the Segmentation Fault is `Event recieved: "edit"`. Just providing this in case it might be related.

Here is the source file that builds and installs rdm: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=redis-desktop-manager

**Comment by uglide** [comment]
@lots0logs @modiho I've reproduced the crash on Arch with Gnome desktop env. Looks like Qt 5.12.3 from the standard arch repo is broken. 
Unfortunately, I do not have time to look into it, so I recommend to install snapd on your system and enjoy the official snap build.

PS: I hope now it's clear why I decided to use snap for RDM packaging on Linux

**Comment by modiho** [comment]
@uglide Thanks for looking into it so far!

**Comment by modiho** [comment]
With latest qt5 version, the crashes are gone for me. Try updating @lots0logs, maybe we can close the issue.

**Comment by uglide** [comment]
@modiho thank's for good news :)

**Comment by lots0logs** [comment]
Yep, its working fine now :+1:
