### ISSUE TITLE
Input field in Select File Control should be read-only on macOS to not mislead users.

### ISSUE THREAD

**Issue by cuongthetran** [redis/RedisDesktopManager#4698]
**Describe the bug**
I am using Redis Desktop Manager 2019.3.20 and every time I try to connect to redis server via ssh, I got the following error:

Connection: Disconnect on error: SSH Connection error(Authentication Error): Unable to extract public key from private key file: Unable to open private key file

**Environment:**
 - OS & version: [OS X]

**Comment by uglide** [comment]
@cuongthetran Please use 
![image](https://user-images.githubusercontent.com/1655867/64109881-48606000-cd89-11e9-8899-5120ee445985.png) this button near input field to select private key using system file dialog.

Due to sandboxing RDM is allowed to open files which was selected by user in open/save dialogs.

**Comment by cuongthetran** [comment]
Hi @uglide ,
Thanks. That works.
