### ISSUE TITLE
Cant scroll on Db keys

### ISSUE THREAD

**Issue by fintechyazilim** [redis/RedisDesktopManager#4712]
I have 2000 Items (keys)  on the db0
i can't scroll down/up  by using scrollbar even i cant use up/down/home/end/pgdn and pgup buttons.

The only way is to use mouse scroll wheel

Windows 10 1903
RDM 2019.3.150

**Comment by uglide** [comment]
@fintechyazilim Could you provide more details on the issue? I cannot reproduce it on my Windows 10 1903 setup:

![ezgif-5-1125bb0089e5](https://user-images.githubusercontent.com/1655867/66658808-eb3eb080-ec4a-11e9-9a1a-2f27397a8205.gif)

**Comment by fintechyazilim** [comment]
Hi Igor,

I can scroll by mouse but when i need to use down-up arrows to navigate i
have to press TAB once and then up/down works.
Home, End, PageUp and PageDown buttons never works.
As you can see at the attached video, scroll bar doesn't work.
When i move the mouse over the scroll bar the cursor is changing to
resizing mode, you can see it clearly on the video.

Thank you for your help.
Regards,
Serhan.




Igor Malinovskiy <notifications@github.com>, 11 Eki 2019 Cum, 17:17
tarihinde şunu yazdı:

**Comment by fintechyazilim** [comment]
Hi Igor,

I can scroll by mouse but when i need to use down-up arrows to navigate i have to press TAB once and then up/down works.
Home, End, PageUp and PageDown buttons never works.
As you can see at the attached video, scroll bar doesn't work. 
When i move the mouse over the scroll bar the cursor is changing to resizing mode, you can see it clearly on the video.

Thank you for your help.
Regards,
Serhan.
![RDM_Scroll_Bug](https://user-images.githubusercontent.com/42867301/66701611-a2e4c880-ed06-11e9-8dcb-202a52678c74.gif)

**Comment by janich** [comment]
I agree. 
Maybe it's because of many items or connections, I dont know, but the windows version doesn't seem to work very well. 

Im not here to rant, but this feedback could very well be true for other windows users as well:
- Arrows dont scroll
- Pageup/down works only sometimes
- Cant use mouse to drag the slider (up/down) in the left window pane with the keys (it will capture the resize function instead OR sometimes scroll in a very laggy way)
- Loading keys can be very slow (even for 100-200kb keys)
- Loading large keys (1mb+) is almost impossible and can trigger crashes
- Marking all text in a key (to copy it) is not possible (it goes into a stale non responding state when trying)
- Cancelling bulk stuff (like cancelling in the middle of deleting a few 1000 keys) is not possible - it ignores your input
- Auto updating feature resets scroll to top of window

Been using Redisdesktopmanager for ~2 years now and it's sadly been the same all along (on 2-3 different windows computers). 

Current RedisDesktop: Newest
Current windows: Windows 10 Pro (1903) (Build 18362.356)

**Comment by uglide** [comment]
@janich 
First of all thanks for your feedback.
Unfortunately, RDM is tightly bound to issues and bugs in Qt 5 framework.
This annoying bug with scrollbar appears in some unpredictable circumstances. My guess that it's somehow connected to Qt automatic app scaling, screen resolution and GPU hardware combinations.

@fintechyazilim  @janich  Could you provide following details:
- GPU hardware & models
- Screen physical sizes & resolutions
- Windows scaling factor for each/main screen

I hope to receive more details from you to finally be able to reproduce this bug and fix it ASAP.

**Comment by uglide** [comment]
@fintechyazilim @janich Could you please also make experiment by running rdm.exe in terminal like that:
1. Open in file explorer installation folder of RDM
2. type `cmd.exe` in path bar to open terminal
3. set env var: `set QT_AUTO_SCREEN_SCALE_FACTOR=0`
4. run `rdm.exe`

**Comment by fintechyazilim** [comment]
Hi,

My Computer is Dell XPS 9570

   - GPU hardware & models
   * NVIDIA(R) GeForce(R) GTX 1050Ti with 4GB GDDR5 *
   - Screen physical sizes & resolutions
   *15.6" 4K Ultra HD (3840 x 2160) InfinityEdge Anti-Reflective Touch
   IPS100% AdobeRGB 400-Nits display*
   - Windows scaling factor for each/main screen
   *%100*


And i did all you told about in your second email but nothing changed.

Best Regards,
Thank you.

Igor Malinovskiy <notifications@github.com>, 24 Eki 2019 Per, 13:29
tarihinde şunu yazdı:

**Comment by janich** [comment]
Hi

Im on a Lenovo T550 with Win10 Pro.

I tried executing rdm.exe from both commandline and a batchjob with env var set, but same - nothing changed.

**Comment by Jaben** [comment]
Same issue here with 4K monitor.

**Comment by uglide** [comment]
@Jaben @janich @fintechyazilim Please try 2020.0-beta1 (from Preview Builds tab on https://redisdesktop.com/subscriptions)

**Comment by fintechyazilim** [comment]
It works perfect on my computer now.
Thank you.

Igor Malinovskiy <notifications@github.com>, 9 Nis 2020 Per, 18:31
tarihinde şunu yazdı:

**Comment by fintechyazilim** [comment]
It works correctly on my computer with the version 2020.0.186

**Comment by uglide** [comment]
Great, thanks for testing!
