### ISSUE TITLE
Subscription agreement violates GPL

### ISSUE THREAD

**Issue by Arcturuss** [redis/RedisDesktopManager#4746]
There is a section in subscription agreement on https://redisdesktop.com/eula that clearly violates GPLv3. i.e.:

> (B) Customer may not:
> (ii) Rent, lease, modify, adapt, create derivative works of, distribute, sell, or transfer the Product;

GPLv3 explicitly grants the rights to modify and distribute licensed software (including binaries). And it forbids further restriction of that rights. 

**Expected behavior**
Because source code in this repository is licensed under GPLv3, any agreement regulating  distribution (binaries and derivative works included) should be GPL-compliant.

**Comment by uglide** [comment]
Hello @Arcturuss 

As the copyright holder, of most of the code in this repository I have the right to distribute, **my** code and derivative works under multiple licenses including (but not limited to :) ) GPLv3 and EULA published on redisdesktop.com.

Some code in this repo is not owned by me (like code from PRs and from other open-source projects) but binaries of RDM are compliant with GPLv3 (and all other more permissive open-source lincenses) because all source code is available in this repo on Github.

Double licensing is commonly used in software, good examples are: Qt (lgpl v3) and intellij-community (apache 2.0)

if you have profound knowledge in software licensing and/or you have any questions or suggestions please share it here.

Let's discuss it :)
