### ISSUE TITLE
connection error permission denied

### ISSUE THREAD

**Issue by DarexMQ** [redis/RedisDesktopManager#4759]
![image](https://user-images.githubusercontent.com/5321774/71305229-74bcec80-240b-11ea-852a-b141f8f53490.png)

Deepin system, this error occurred when connecting redis, how to solve it.
sudo to run the same unsuccessful

**Comment by ElanZh** [comment]
I know it，it because the snap enable apparmor，a permissions ctrl system.

我也碰到了，这是因为snap启用了apparmor这个权限控制系统

but I don't know what permissions RDM need，and I don't know how to config the apparmor.

我不知道RDM需要什么权限，就是知道了，我也不会配这个apparmor破玩意儿。

It also make Docker permission problem, because container need port ... now my docker container can't start unless

这玩意还会让docker容器启动失败，因为容器需要占用端口。。。我所有的容器都无法启动了，除非你把他卸了：

```sudo apt remove apparmor```

but ，if you remove it，all apps installed use snap will can't start... fuck, I just want install a software I'm not ops.

但是，卸了它，所有使用snap安装的软件都不能用了，我tnd，我只是想装个软件而已，没想当运维。

**Comment by uglide** [comment]
Snapd is broken on Deepin Linux https://forum.snapcraft.io/t/deepin-debian-9-snaps-have-no-internet-connection/11295 
I recommend switching to any other Linux distro with better snapd support
