### ISSUE TITLE
Connection over kubernetes

### ISSUE THREAD

**Issue by mallowigi** [redis/RedisDesktopManager#4968]
Hi,

I've bought RDM a while ago and was very happy with the results. However since then our company moved their servers to kubernetes and redis is now blocked from outside. The only way to access it would be to ssh into a pod with kubeconfig.

I was wondering if there is a way to make RDM make use of kubeconfig as well, to connect to specific pods.

Thanks.

**Comment by uglide** [comment]
Hello,

RDM cannot use `kubeconfig` to connect to pods because under the hood `kubeconfig exec` is just POST request to k8s REST API upgraded to SPDY/Websocket

To be able to connect to redis-server in RDM you can use:
1. Forward port
```
kubectl port-forward --namespace default svc/hello-redis-master 6379:6379 &
```
2. Expose redis-server with NodePort and *restrict access with Firewall*
https://kubernetes.io/docs/concepts/services-networking/service/#nodeport
3. Add pod with running ssh server (or vpn server) to your k8s cluster and use SSH tunnel in RDM to reach all redis-server inside your cluster
