### ISSUE TITLE
Filter is only applied to the current page and not to all the rows

### ISSUE THREAD

**Issue by Manumaguana** [redis/RedisDesktopManager#5067]
Create a new store in redis and add 30000 rows in it as R_00000, R_00001 etc
Load Redis Desktop Manager and select the store
Add a Filter like R_ and see that the filter is only applied to the current page.

What is the point to have a filter per Page and not for the whole table?
Windows 10 with latest Redis Desktop Manager.

**Comment by uglide** [comment]
Hello,
To search the whole table RDM needs to load all values and it may be a time-consuming operation on large keys, that's why by default RDM applies filter only to the current page and to apply it to the whole "table" you need to press "Full Search" button:

![image](https://user-images.githubusercontent.com/1655867/122013128-8e53b000-cdc6-11eb-9820-11de39a13a66.png)

**Comment by Manumaguana** [comment]
Full search button does not appear in my RDM version 0.9.3.817

What version has that full search option?

**Comment by uglide** [comment]
The latest version (2021.4) has this functionality. This feature was added in the 2019 or 2020 version branch.
