### ISSUE TITLE
Viewing (and editing) string as JSON is incorrect

### ISSUE THREAD

**Issue by dandersonCCLI** [redis/RedisDesktopManager#5102]
When viewing a string as JSON, all spaces have been stripped out.  Apart from, it seems, when there is something that looks like a date - it adds a few random spaces in then.
Whilst this is annoying, it causes problems if an edit is made, as it saves it back without spaces.

Viewing the string as plan text works fine.

**Expected behaviour**
I would expect the JSON display to display strings as they should be, and not randomly remove or add spaces.

**Screenshots**
For example, here's a string viewed as JSON:
![image](https://user-images.githubusercontent.com/89457322/130607294-1051a28c-edff-4afb-bfe3-ea0967f7e11d.png)

And the same string viewed as plain text:
![image](https://user-images.githubusercontent.com/89457322/130607343-1ce09802-c991-4157-b283-9ae3faf96dc4.png)

You can see the spaces removed from StatusDescription, ServiceCenterTZLabel, and TimeZoneId.   You can also see the spaces inserted in StatusData (always after a colon I notice)

**Environment (please complete the following information):**
 - OS & version: Windows 10 21H2
 - Redis-Server version: 4.0.14
 - RDM - GUI for Redis version: 2021.7.79

**Comment by uglide** [comment]
Hello,

Thanks for the bug report.

 A small note on the default JSON minification: Since Redis is the in-memory data store RDM tries to optimize your values and store JSON minified. Minification allows reducing memory footprint by 30%+ and in general case is considered as good practice as well as usage of other serialization formats with build-in compression/binary minification like MsgPack, etc
