### ISSUE TITLE
Snap Size is Painfully Large

### ISSUE THREAD

**Issue by Carter12s** [redis/RedisDesktopManager#5219]
**Describe the bug**
For what this application provides a 1.1GB download is pretty painful and took ~20 minutes on coffee shop wifi. 

**To Reproduce**
`sudo snap install redis-desktop-manager`
I did it on Ubuntu 20.04 Mar 22nd 2022

Examining size of resulting snap:
`1.1G	/var/lib/snapd/snaps/redis-desktop-manager_599.snap`

**Expected behavior**
Blender ships in 200MB
Gimp ships in 250MB
Audacity ships in 100MB
Maybe I'm just grumbling and this is a reality of distributing via snap, but I really think it will improve user experience if app can ship in <100MB

**Comment by uglide** [comment]
Hello @Carter12s 
Your point is absolutely valid. Furthermore, this packaging issue was fixed in snap already https://github.com/RedisDesktop/redisdesktopmanager-snap/commit/726aa7ab7d79ea854182fb20b9d8eb9183719f8b
but it's still only in the edge channel for now. I will release it to stable channel today.

**Comment by uglide** [comment]
612 build was released to the stable channel. The size is about 280Mb so should be much easier to download.
