### ISSUE TITLE
Restore icons with color

### ISSUE THREAD

**Issue by KentACar** [redis/RedisDesktopManager#5225]
I experience the new icons completely without color as MUCH worse. It's nice with an icon but gets so much better with color. Feels much easier to choose wrong now. You also do not always have access to tooltips.

Do again, do better, do right :-)

**Comment by uglide** [comment]
@KentACar thanks for the feedback. Most users prefer dark themes that's why colorful icons are too bright and "burn eyes". Also, the current approach allowed to set color for each connection <img width="400" src="https://user-images.githubusercontent.com/1655867/155361009-fef81d65-2f06-415c-8a1b-fc3ac18894cd.png" />

I'm open to suggestions and proposals but at this point, I don't see a better way to solve mentioned problems.
