### ISSUE TITLE
Connections Import/Export doesn't work on Linux

### ISSUE THREAD

**Issue by uglide** [redis/RedisDesktopManager#5236]

**Comment by gioisco** [comment]
The problem is present in the latest version (at the time I'm writing):
- flatpak 2022+577a8e5
- snap package 2022.3+093dfac3 (latest/edge)
(they seem the same version).

I discover a workaround coping the **connections.json** file.
For flatpak it's placed in: `~/.rdm/connections.json`
For snap it's placed in: `~/snap/redis-desktop-manager/common/.rdm/connections.json
`
The snap path is not mentionad in the documentation: https://docs.resp.app/en/latest/faq/#where-is-the-connections-config-stored

**Comment by gioisco** [comment]
For export:
1) Click on Export Connections
2) The RESP app open the dialog for select path and set filename
3) Click on Save, the dialog closed, but the file was not stored.

It could be useful to have an error messege.

**Comment by uglide** [comment]
Fixed in 2022.4.2 (Snapcraft build 626)
