### ISSUE TITLE
DB restore from dump

### ISSUE THREAD

**Issue by Dyachenko** [redis/RedisDesktopManager#58]
It will be nice if RDM be able to export data from redis DB as dump and restore DB from dump.
##

**Comment by uglide** [comment]
Since making rdb dump is not really useful because it's much easier to make `bgsave` and use SCP to copy dump file I'm reducing the scope of this feature to importing from rdb dumps:

![image](https://user-images.githubusercontent.com/1655867/59147537-a50be300-8a05-11e9-9bf0-b4803791c801.png)

(Finally) coming soon in 2019.2
